MySQL:
  dsn: "root:12345678@tcp(127.0.0.1)/ginchat?charset=utf8mb4&parseTime=True&loc=Local"
Redis:
  addr: "182.92.132.85:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIDleConn: 30

port:
  server: "8080"
  udp: 3001